language: python
python:
  - "2.7"
  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov

notifications:
   webhooks: https://coveralls.io/webhook?repo_token=cwptp15kEnSH8qBehr0WTfrds5wAA52wf

# command to run tests
script:
  - coverage erase
  - pytest # or py.test for Python versions 3.5 and below
  - nosetests --with-coverage --cover-package=app,models
  - coverage report -m
  
after_success:
  - coveralls
  - codecov
deploy:
  skip_cleanup: true