language: python
python:
  - "2.7"
  - "3.5"

# command to install dependencies
install:
  - pip install --user -r requirements.txt
  - pip install coveralls

notifications:
   webhooks: https://coveralls.io/webhook?repo_token=cwptp15kEnSH8qBehr0WTfrds5wAA52wf

# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
  - nosetests --with-coverage
after_success:
  - coveralls
deploy:
  skip_cleanup: true