language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov

notifications:
   webhooks: https://coveralls.io/webhook?repo_token=jAIa5YodnvyloADxpizQ6Fhyg24O38k4b

# command to run tests
script:
  - coverage erase
  - nosetests --with-coverage --cover-package=app
  - coverage report -m
  
after_success:
  - coveralls
  - codecov
deploy:
  skip_cleanup: true